apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: 837553127105.dkr.ecr.us-east-1.amazonaws.com/react-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
